"""
repo_to_markdown.py
-------------------
Dumps a folder (or the whole repo) into a single markdown file
suitable for pasting into an AI chat for code review.

Usage:
    python repo_to_markdown.py                        # dumps entire current dir
    python repo_to_markdown.py modules                # dumps only the modules/ subfolder
    python repo_to_markdown.py . --out context.md     # custom output file name
    python repo_to_markdown.py modules --max-kb 50    # skip files larger than 50KB
"""

import os
import argparse
from pathlib import Path

# Files/folders to always skip
SKIP_DIRS = {
    ".git", ".venv", "venv", "__pycache__", "node_modules",
    ".mypy_cache", ".pytest_cache", "dist", "build", "logs", ".uv"
}
SKIP_EXTENSIONS = {
    ".pyc", ".pyo", ".pyd", ".so", ".dll", ".exe",
    ".png", ".jpg", ".jpeg", ".gif", ".ico", ".svg", ".webp",
    ".zip", ".tar", ".gz", ".whl",
    ".xlsx", ".xls", ".csv",  # usually too large / binary
    ".lock",                   # uv.lock / poetry.lock — noisy
}

# Language hint map for fenced code blocks
EXT_TO_LANG = {
    ".py": "python",
    ".sh": "bash",
    ".md": "markdown",
    ".json": "json",
    ".yaml": "yaml",
    ".yml": "yaml",
    ".toml": "toml",
    ".txt": "text",
    ".env": "bash",
    ".html": "html",
    ".js": "javascript",
    ".ts": "typescript",
    ".sql": "sql",
    ".r": "r",
}


def collect_files(root: Path, max_bytes: int) -> list[Path]:
    files = []
    for path in sorted(root.rglob("*")):
        # Skip hidden dirs and known noisy dirs
        if any(part.startswith(".") or part in SKIP_DIRS for part in path.parts):
            continue
        if not path.is_file():
            continue
        if path.suffix.lower() in SKIP_EXTENSIONS:
            continue
        if path.stat().st_size > max_bytes:
            print(f"  [skip — too large] {path}")
            continue
        files.append(path)
    return files


def build_markdown(root: Path, files: list[Path]) -> str:
    lines = []
    lines.append(f"# Code Export: `{root.name}/`\n")
    lines.append(f"**{len(files)} files included** | Generated by repo_to_markdown.py\n")
    lines.append("---\n")

    # Table of contents
    lines.append("## Table of Contents\n")
    for f in files:
        rel = f.relative_to(root)
        anchor = str(rel).replace("/", "").replace("\\", "").replace(".", "").replace("_", "").lower()
        lines.append(f"- [`{rel}`](#{anchor})\n")
    lines.append("\n---\n")

    # File contents
    for f in files:
        rel = f.relative_to(root)
        lang = EXT_TO_LANG.get(f.suffix.lower(), "")
        lines.append(f"## `{rel}`\n")
        try:
            content = f.read_text(encoding="utf-8", errors="replace")
        except Exception as e:
            content = f"[Could not read file: {e}]"
        lines.append(f"```{lang}")
        lines.append(content)
        lines.append("```\n")
        lines.append("---\n")

    return "\n".join(lines)


def main():
    parser = argparse.ArgumentParser(description="Export a repo subfolder to markdown.")
    parser.add_argument(
        "folder",
        nargs="?",
        default=".",
        help="Folder to export (default: current directory)"
    )
    parser.add_argument(
        "--out",
        default=None,
        help="Output filename (default: <folder_name>_context.md)"
    )
    parser.add_argument(
        "--max-kb",
        type=int,
        default=100,
        help="Skip files larger than this many KB (default: 100)"
    )
    args = parser.parse_args()

    root = Path(args.folder).resolve()
    if not root.exists():
        print(f"Error: '{root}' does not exist.")
        return

    max_bytes = args.max_kb * 1024
    out_name = args.out or f"{root.name}_context.md"
    out_path = Path(out_name)

    print(f"Scanning: {root}")
    files = collect_files(root, max_bytes)
    print(f"Found {len(files)} files to include.")

    md = build_markdown(root, files)
    out_path.write_text(md, encoding="utf-8")

    size_kb = out_path.stat().st_size / 1024
    print(f"\nWritten to: {out_path}  ({size_kb:.1f} KB)")
    if size_kb > 200:
        print("  ⚠️  File is large. Consider passing a specific subfolder, e.g.:")
        print(f"       python repo_to_markdown.py modules")


if __name__ == "__main__":
    main()
