--- SOURCE: https://www.anaheim.net/332/Past-Anaheim-City-Officials ---

![Loading](https://www.anaheim.net/Common/images/ajax-loader.gif)
Loading
[Skip to Main Content](https://www.anaheim.net/332/Past-Anaheim-City-Officials#cc622007e8-e6c7-4d3b-8aef-85364de4b3e8)
![Anaheim, CA](https://www.anaheim.net/ImageRepository/Document?documentID=41690)
[![Home page](https://www.anaheim.net/ImageRepository/Document?documentID=41692)](https://www.anaheim.net/)
[![Go to Site Search](https://www.anaheim.net/ImageRepository/Document?documentID=41694)](https://www.anaheim.net/Search/Results) Search
  * [![Facebook](https://www.anaheim.net/ImageRepository/Document?documentID=41698) ](https://www.anaheim.net/facebook)


  * [![Twitter](https://www.anaheim.net/ImageRepository/Document?documentID=41705) ](https://www.anaheim.net/twitter)


  * [![Instagram](https://www.anaheim.net/ImageRepository/Document?documentID=41699) ](https://www.anaheim.net/instagram)


  * [![YouTube](https://www.anaheim.net/ImageRepository/Document?documentID=41708) ](https://www.anaheim.net/youtube)


  * [![Newsletter](https://www.anaheim.net/ImageRepository/Document?documentID=41697) ](https://www.anaheim.net/list.aspx)


  1. [ Pay & Apply ](https://www.anaheim.net/6162/Pay-Apply)
  2. [ Find & Report ](https://www.anaheim.net/6158/Find-Report)
  3. [ Community Info ](https://www.anaheim.net/6161/Community-Info)
  4. [ Departments ](https://www.anaheim.net/148/Departments)


  1. [Home](https://www.anaheim.net/)
  2. [Departments](https://www.anaheim.net/148/Departments)
  3. [City Council](https://www.anaheim.net/173/City-Council)
  4. Past Anaheim City Officials


#  Past Anaheim City Officials 
## Incorporation of the City of Anaheim in 1870
  

The California Legislature passed at the 18th Session (1869-1870) an act for the incorporation of the City of Anaheim, approved February 10, 1870.
Year  
| Position  
| Name  
  
---|---|---  
1870 | Mayor | Max Strobel  
1871 | Mayor | Henry Kroeger  
1872 | Mayor | Henry Kroeger  
##    
Charter
  

Charter revoked by act of Legislature approved March 7, 1872, repealed. The City of Anaheim was on the 6th day of December 1876, duly incorporated under act of the Legislature of the State of California, approved April 9, 1856 by the Board of Supervisors of Los Angeles County.
Year  
| Position  
| Name  
  
---|---|---  
1876 | President | John Fischer  
1877 | President | Theodore Reiser  
1878 | President | L.W. Kirby  
1879 | President | B.F. Seibert  
1880 | President | B.F. Seibert  
1881 | President | B. Dreyfus  
1882 | President | B. Dreyfus  
1883 | President | J.P. Zeyn  
1884 | President | F.A. Korn  
1885 | President | R.J. Northam  
1886 | President | R.J. Northam  
1887 | President | A. Rimpau  
1888 | President | Frank Ey  
##    
Anaheim Becoming a City of the 6th Class
  

Reorganization of the town of Anaheim to become a city of the 6th class under the General Laws of the State of California, carried at an election held in the town of Anaheim, Monday, the 4th day of June, 1888, in accordance with an Act of the Legislature approved March 13, 1883.
Year  
| Position  
| Name  
  
---|---|---  
**1888** |  **Election****  
** | **June 4, 1888  
**  
1888 | President | Frank Ey  
1890 | President | Theodore Reiser  
1892 | President | W.A. Witte  
1894 | President | Charles O. Rust  
1896 | President | Charles O. Rust  
1898 | President | Charles O. Rust  
1900 | President | Joseph Helmson  
1902 | President | Julius J. Schneider  
1904 | President | Charles O. Rust  
1906 | President | Charles O. Rust  
1908 | President | Charles O. Rust  
1910 | President | Charles O. Rust  
1912 | President | Max Nebelung  
1914 | President | John H. Cook  
1916 | President | Julius Schneider  
1918 | President | John J. Dwyer  
1920 | President | William Stark  
1922 | President | William Stark  
1924 | President | E.H. Metcalf  
**1925** | **Recall Election** | **February 3, 1925**  
1925   
| President | Perry W. Mathis  
1926 | President | Perry W. Mathis resigned,Carl F. Leonard Elected.  
1928 | President | Louis E. Miller  
1930 | Mayor | Louis E. Miller  
1932 | Mayor | Fred H. Koesel  
1934 | Mayor | Charles H. Mann  
1936 | Mayor | Charles H. Mann  
1938 | Mayor | Charles H. Mann  
1940 | Mayor | Charles A. Pearson  
**1942** | **Election** |  **April 14, 1942**  
  
1942  
| Mayor | Charles A. Pearson  
**1944** | **Election  
** |  **April 11, 1944****  
**  
1946 | Mayor | Charles A. Pearson  
**1946** | **Election  
** |  **April 9, 1946****  
** |   
  
1946  
| Mayor | Charles A. Pearson  
1948 | Mayor | Charles A. Pearson  
1950 | Mayor | Charles A. Pearson  
1952 | Mayor | Charles A. Pearson  
**1954** | **Election  
** |  **April 13, 1954****  
** |   
  
1954  
| Mayor | Charles A. Pearson  
1956 | Mayor | Charles A. Pearson  
1958 | Mayor | Charles A. Pearson  
1959 | Mayor | Charles A. Pearson resigned, A.J. Schutte Elected  
1960 | Mayor | A.J. Schutte  
1962 | Mayor | Rector L. Coons  
1964 | Mayor | Rector L. Coons  
1964/1965 | Mayor | Odra Chandler  
1965/1968 | Mayor | Fred T. Krein  
1968/1969 | Mayor | Cal Pebley  
1969/1970 | Mayor | Ralph Clark  
1970/1976 | Mayor | Jack Dutton  
1976/1978 | Mayor | W.J. "Bill" Thom  
1978/1982 | Mayor | John Seymour  
1982/1986 | Mayor | Don Roth  
1986/1988 | Mayor | Ben Bay  
1988/1992 | Mayor | Fred Hunter  
1992/2002 | Mayor | Tom Daly  
2002/2010 | Mayor | Curt Pringle  
2010/2018 | Mayor | Tom Tait  
  
2018/2022 | Mayor | Harry Sidhu _resigned May 24, 2022_  
  1. [Anaheim Mayor Ashleigh Aitken](https://www.anaheim.net/5174/Anaheim-Mayor-Ashleigh-Aitken)
  2. [Mayor Pro Tem Carlos A. Leon](https://www.anaheim.net/2314/Mayor-Pro-Tem-Carlos-A-Leon)
  3. [Council Member Ryan Balius](https://www.anaheim.net/3522/Council-Member-Ryan-Balius)
  4. [Council Member Natalie Rubalcava](https://www.anaheim.net/3523/Council-Member-Natalie-Rubalcava)
  5. [Council Member Norma Campos Kurtz](https://www.anaheim.net/3524/Council-Member-Norma-Campos-Kurtz)
  6. [Council Member Kristen Maahs](https://www.anaheim.net/3521/Council-Member-Kristen-Maahs)
  7. [Council Member Natalie Meeks](https://www.anaheim.net/5175/Council-Member-Natalie-Meeks)
  8. [Council Meeting Calendar](https://www.anaheim.net/DocumentCenter/View/67140/2026-City-Council-Meeting-Calendar)
  9. [City Council Agendas](http://local.anaheim.net/docs_agend/questys_pub/)
  10. [View City Council Meetings](https://www.anaheim.net/2142/View-City-Council-Meetings)
  11. [Public Participation at a City Council Meeting](https://www.anaheim.net/344/Public-Participation-at-a-City-Council-M)
  12. [Request a Proclamation or Certificate](https://www.anaheim.net/FormCenter/City-Administration-10/Request-a-Proclamation-or-Certificate-125)
  13. [Past Anaheim City Officials](https://www.anaheim.net/332/Past-Anaheim-City-Officials)


  1. ![Anaheim](https://www.anaheim.net/ImageRepository/Document?documentId=41696)
  



### Contact Us
  1. City of Anaheim  
200 S. Anaheim Blvd.  
Anaheim, CA 92805  
([714) 765-4311](tel:714-765-4311)  
[Dial 311](tel:%20311)


### [Helpful Links](https://www.anaheim.net/QuickLinks.aspx?CID=374)
  1. [City Council Video](https://www.anaheim.net/2142/Council-Meeting-Video)
  2. [FY 2025/26 Adopted Budget](https://anaheim.net/Archive.aspx?AMID=38&Type=Recent)
  3. [News and Media Center](https://www.anaheim.net/1737/News-Media-Center)
  4. [Anaheim Newsletter](https://www.anaheim.net/1725/Anaheim-Newsletter)
  5. [Visit Anaheim](http://visitanaheim.org/)
  6. [Boards & Commissions](https://www.anaheim.net/176/Boards-Commissions)


/QuickLinks.aspx
### [Quick Links](https://www.anaheim.net/QuickLinks.aspx?CID=242)
  1. [Contact Us](https://www.anaheim.net/directory.aspx)
  2. [Home](https://www.anaheim.net/)
  3. [Site Map](https://www.anaheim.net/sitemap)
  4. [Accessibility](https://www.anaheim.net/Accessibility)
  5. [Disability & Civil Rights Program ](https://www.anaheim.net/1740/Disability-Civil-Rights-Program)
  6. [Copyright Notices](https://www.anaheim.net/site/copyright)


/QuickLinks.aspx
Government Websites by [CivicPlus®](https://connect.civicplus.com/referral)
## Loading
Loading 
Do Not Show Again Close
Arrow Left Arrow Right
Slideshow Left Arrow Slideshow Right Arrow
Close **×**
